---
title: "Usando Regressão Linear para Explicar a votação de Deputados"
author: "Gustavo Monteiro"
date: "October 3, 2018"
output: html_document
---

```{r warning=FALSE, echo=FALSE, message=FALSE}
library(tidyverse)
library(here)
```

```{r}
eleicoes_data <- read_csv(
  here('./eleicoes_2006_e_2010.csv'), 
  local=readr::locale("br"),
  col_types = cols(
    ano = col_integer(),
    sequencial_candidato = col_character(),
    quantidade_doacoes = col_integer(),
    quantidade_doadores = col_integer(),
    total_receita = col_double(),
    media_receita = col_double(),
    recursos_de_outros_candidatos.comites = col_double(),
    recursos_de_pessoas_fisicas = col_double(),
    recursos_de_pessoas_juridicas = col_double(),
    recursos_proprios = col_double(),
    `recursos_de_partido_politico` = col_double(),
    quantidade_despesas = col_integer(),
    quantidade_fornecedores = col_integer(),
    total_despesa = col_double(),
    media_despesa = col_double(),
    votos = col_integer(),
    .default = col_character()))
```

```{r}
data_2006 = eleicoes_data %>% 
  filter(ano == 2006)

data_2010 = eleicoes_data %>% 
  filter(ano == 2010)
```

```{r}
# participação feminina
data_2006_genner_general = data_2006 %>% 
  group_by(sexo) %>% 
  summarise(num = n())

parties_with_more_candidates_2006 = data_2006 %>% 
  group_by(partido) %>% 
  summarise(num = n()) %>% 
  top_n(5, num)

data_2006_genner = data_2006 %>% 
  filter(partido %in%  parties_with_more_candidates_2006$partido) %>% 
  group_by(sexo, partido) %>%
  summarise(num = n()) %>% 
  group_by(partido)
```

```{r}
# escolaridade
schooling = data_2006 %>% 
  group_by(grau) %>% 
  summarise(num = n())

accupation = data_2006 %>% 
  group_by(ocupacao) %>% 
  summarise(num = n()) %>% 
  top_n(10, num)
```

```{r}
paries_with_more_money_2006 = data_2006 %>% 
  group_by(partido) %>% 
  summarise(
    total = sum(total_receita), 
    self = sum(recursos_proprios) + sum(recursos_de_partido_politico),
    donations = sum(recursos_de_pessoas_fisicas) + sum(recursos_de_pessoas_juridicas),
    by_people = sum(recursos_de_pessoas_fisicas),
    by_companies = sum(recursos_de_pessoas_juridicas)) %>% 
  top_n(10, total) 

```

